apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: access-matrix
spec:
  version: v0.5.0
  homepage: https://github.com/corneliusweig/rakkess
  shortDescription: Show an access matrix for server resources
  platforms:
    - selector:
        matchLabels:
          os: linux
      uri: https://github.com/corneliusweig/rakkess/releases/download/v0.5.0/rakkess.tar.gz
